### ISSUE TITLE
Exposing item values

### ISSUE THREAD

**Issue by pigsyn** [shagu/ShaguValue#1]
Hello,

Are you willing to expose ShaguValue item values from data ?
Something like this:

  **ShaguValue = {
    Data = data 
  }**

It could be nice for auction addons like AUX, then you could populate AUX database for items that came after 1.8 with a simple macro like this:

`/run for id=1,30000 do 
  local i=ShaguValue.Data[id] 
  if i then 
    local _, _, sell, buy = strfind(i, "(.*),(.*)")
    aux_merchant_sell[id] = sell
    aux_merchant_buy[id] = buy
  end 
end`

Informant (from auctioneer) never had values for new items introduced from 1.8 to 1.12 in vanilla. (3.X branch)

They added values in early TBC but had a lot of errors and developed an update mechanism from what I can understand from their SVN repo. Values are still wrong in their WOTLK release for 1.8+ items.

I tested it myself and I have all item prices now.

**Comment by shagu** [comment]
Hi,

Thanks for your input. But the short answer is "No".

I'm not going to populate the global space with that data, those who really want to use your macro can easilly remove the `local` in front of `data` for a single login and import it. It's also not in my responsibility to fix bad values in aux or auctioneer. 

In my opinion, you should instead create an issue on the aux bugtracker and ask the author if he will include the data in his addon. It can easilly obtained by any blizzlike 1.12 server database.

Cheers,
Shagu

**Comment by Jonas1312** [comment]
I added this to ShaguValue lua:

```markdown
-- Expose a global function to retrieve the vendor sell price for an item.
-- This function accepts either an item ID (number) or an item link (string).
function GetVendorPriceForItem(input)
  local itemID = nil
  if type(input) == "number" then
    itemID = input
  elseif type(input) == "string" then
    -- Use string.find to extract the numeric itemID from the link.
    local startIdx, endIdx, id = string.find(input, "item:(%d+):")
    if id then
      itemID = tonumber(id)
    end
  end

  if itemID and data[itemID] then
    -- Use string.find to capture the sell and buy prices from the data string.
    local s, e, sell, buy = string.find(data[itemID], "(%d+),(%d+)")
    if sell then
      return tonumber(sell)
    end
  end
  return nil
end

```

not local so it can be used in a macro for example
