### ISSUE TITLE
TBC version

### ISSUE THREAD

**Issue by FrostShock** [shagu/ShaguValue#2]
Excuse me, I would like to ask you if it's possible to create a TBC 2.4.3 version?

**Comment by shagu** [comment]
Sure :)

TBC support added with: https://github.com/shagu/ShaguValue/commit/c96cdea177e3c0767e9be7861cc8059d9ddcf614 https://github.com/shagu/ShaguValue/commit/8081d3f71a1e441b0606188c86997fab836f8fef https://github.com/shagu/ShaguValue/commit/6f6978554f9fab121a080fe6f704cbfe6c6c2627

**Comment by FrostShock** [comment]
OMG I'm sorry I haven't notice it's for TBC too. I was using it on Vanilla and I was convinced it's only for Vanilla. My apologies.

**Comment by shagu** [comment]
> OMG I'm sorry I haven't notice it's for TBC too. I was using it on Vanilla and I was convinced it's only for Vanilla. My apologies.

Nothing to apologize, it didn't had TBC support. I did it yesterday. :)

**Comment by FrostShock** [comment]
Thank you sir!

Maybe update the description too? As of now it says "A Vanilla Addon to display item sell and buy values on tooltips"
